export const ENV_VARS = {
    PORT: 'PORT',
    MONGODB_USER: 'MONGODB_USER',
    MONGODB_PASSWORD: 'MONGODB_PASSWORD',
    MONGODB_DB_HOST: 'MONGODB_DB_HOST',
    MONGODB_DB_DATABASE: 'MONGODB_DB_DATABASE',
};
